POST http://localhost:9999/api/tokens
Content-Type: application/json

{
  "username": "vasya",
  "password": "hash"
}

> {% client.global.set("auth_token", response.body.token); %}

###

POST http://localhost:9999/api/tokens
Content-Type: application/json

{
  "username": "vasya",
  "password": "invalid"
}

###

GET http://localhost:9999/api/users/me
Authorization: Bearer {{auth_token}}

###

DELETE http://localhost:9999/
Authorization: Bearer {{auth_token}}

###
###

POST http://localhost:8181/api/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="img.zip"
Content-Type: application/zip

< ./.gitignore
--WebAppBoundary--

###